---

debian_servers:
  hosts:
    debian-srv-01:
      ansible_host: 10.222.34.90

debian_workers:
  hosts:
    debian-wrk-01:
      ansible_host: 10.222.34.91

debian_vms:
  children:
    debian_servers:
    debian_workers:
  vars:
    # This is the user that has SSH access to the machines.
    ansible_user: root

    add_user: udemx
    add_user_home_dir: "/opt/{{ add_user }}"
    add_ssh_public_key: |
      ssh-rsa asd123 user@host

    docker_compose_dir: "{{ add_user_home_dir }}/project"
    docker_project:
      nginx:
        version: 1.27.2
        container_name: nginx
      mariadb:
        version: 11.5.2
        container_name: mariadb
        user: "{{ add_user }}"
        password: ""

    jenkins:
      version: "2.485"
      container_name: jenkins
      location: "{{ add_user_home_dir }}/jenkins"
      agent:
        enabled: true
        version: "3283.v92c105e0f819-1"
        container_name: jenkins-agent
        name: "agent1"
        # Can be provided after manually creating node in Jenkins master
        secret: ""

    registry:
      enabled: true
      version: 2.8.3
      container_name: docker_registry
      ui:
        enabled: true
        version: 2.5.7
        container_name: docker_registry_ui

      
# For 'terraform' commands

terraform:
  hosts:
    localhost:
  vars:
    state: "present"
    # -- Options: proxmox
    provider: proxmox
    proxmox: 
      api_url: "https://192.168.0.2:8006/api2/json"
      api_token_id: "terraform@pam!terraform-token"
      api_token_secret: ""
      target_node: "pve"
      vmid: 900
      template_name: "debian11-cloudinit"
      gateway: "192.168.0.1"
      vm_cores: 1
      vm_memory: 2048
      storage_pool: "local"
      storage_size: "10G"
      ciuser: root
      cipassword: "password"
      ssh_public_key: |
        ssh-rsa asd123 user@host
      name_prefix: "debian11"


