- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Install keyring directory
  ansible.builtin.command:
    cmd: install -m 0755 -d /etc/apt/keyrings
  become: yes

- name: Download Docker GPG key
  ansible.builtin.command:
    cmd: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc

- name: Set permissions on Docker GPG key
  ansible.builtin.command:
    cmd: chmod a+r /etc/apt/keyrings/docker.asc

- name: Add Docker repository to Apt sources
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ docker_deb_version_codename }} stable" > /etc/apt/sources.list.d/docker.list

- name: Install Docker and Docker Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Add `{{ add_user }}` user to the Docker group
  ansible.builtin.user:
    name: "{{ add_user }}"
    groups: docker
    append: yes

- name: Render and copy docker-deamon template
  ansible.builtin.template:
    src: "docker-deamon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "{{ add_user }}"
    group: "{{ add_user }}"
    mode: '0644'
  when: registry.enabled

- name: Restart docker service to apply changes
  ansible.builtin.service:
    name: docker
    state: restarted


