- name: Configure SSH Jail in Fail2Ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/ssh.conf
    content: |
      [sshd]
      enabled = true
      port = 23
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 5

- name: Configure NGINX Jail in Fail2Ban
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/nginx.conf
    content: |
      [nginx-http-auth]
      enabled = true
      port = http,https
      filter = nginx-http-auth
      logpath = /var/log/nginx/error.log
      maxretry = 5

- name: Start and enable Fail2Ban service
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

