- name: Configure SSH
  ansible.builtin.include_tasks: ssh_setup.yaml

- name: Configure new user
  ansible.builtin.include_tasks: user.yaml

- name: Configure Fail2Ban
  ansible.builtin.include_tasks: fail2ban.yaml

- name: Configure git
  ansible.builtin.include_tasks: git.yaml

